# Generated by Django 6.0.3 on 2026-03-11 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_thread_id', models.CharField(max_length=200)),
                ('slack_channel_id', models.CharField(blank=True, max_length=50)),
                ('slack_thread_ts', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_approval', 'Pending Approval'), ('replied', 'Replied'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('gmail_message_id', models.CharField(max_length=200, unique=True)),
                ('raw_message_id', models.CharField(blank=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
