# Generated by Django 6.0.3 on 2026-03-26 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveIntegerField(default=0)),
                ('gmail_attachment_id', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, upload_to='attachments/%Y/%m/')),
                ('downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message')),
            ],
        ),
    ]
