# Generated by Django 5.0.4 on 2026-04-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversation_stale_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_draft',
            field=models.TextField(blank=True),
        ),
    ]
