# Generated by Django 6.0.3 on 2026-03-11 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mc_number', models.CharField(max_length=50, unique=True)),
                ('dot_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('rate_floor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('slack_channel', models.CharField(blank=True, max_length=100)),
                ('slack_channel_id', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#38bdf8', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
