# Generated by Django 6.0.3 on 2026-03-11 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=10)),
                ('ai_summary', models.CharField(blank=True, max_length=300)),
                ('confidence', models.FloatField(default=0.9)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(default='LOW', max_length=10)),
                ('flags', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('is_clean', models.BooleanField(default=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
