# Generated by Django 6.0.3 on 2026-03-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='compliancescan',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scan', to='conversations.message'),
        ),
    ]
