# Generated by Django 5.0.4 on 2026-04-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='subcategory',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
