# Generated by Django 6.0.3 on 2026-03-13 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleServiceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='e.g. rwfreight.com', max_length=200)),
                ('_json_data', models.TextField(blank=True, db_column='json_data')),
                ('pubsub_topic', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Dispatch OS Gmail OAuth', max_length=200)),
                ('client_id', models.TextField(blank=True)),
                ('_client_secret', models.TextField(blank=True, db_column='client_secret')),
                ('redirect_uri', models.CharField(blank=True, help_text='Must match GCP Console exactly, e.g. http://localhost:8000/api/settings/oauth/callback/', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token')),
                ('_access_token', models.TextField(blank=True, db_column='access_token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_bot_token', models.TextField(blank=True, db_column='bot_token')),
                ('channel_safety', models.CharField(blank=True, max_length=50)),
                ('channel_approvals', models.CharField(blank=True, max_length=50)),
                ('channel_compliance', models.CharField(blank=True, max_length=50)),
                ('channel_system', models.CharField(blank=True, max_length=50)),
                ('channel_safety_name', models.CharField(blank=True, max_length=100)),
                ('channel_approvals_name', models.CharField(blank=True, max_length=100)),
                ('channel_compliance_name', models.CharField(blank=True, max_length=100)),
                ('channel_system_name', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slack Settings',
            },
        ),
        migrations.CreateModel(
            name='MailboxSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, choices=[('dispatch', 'Dispatch'), ('safety', 'Safety'), ('billing', 'Billing'), ('general', 'General')], default='dispatch', max_length=50)),
                ('auth_method', models.CharField(choices=[('service_account', 'Service Account (Workspace)'), ('oauth', 'OAuth 2.0 (Gmail / any domain)')], default='oauth', max_length=20)),
                ('watch_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('expired', 'Expired')], default='inactive', max_length=20)),
                ('last_history_id', models.CharField(blank=True, max_length=50)),
                ('watch_expiry', models.DateTimeField(blank=True, null=True)),
                ('watch_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_settings', to='companies.company')),
                ('service_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='settings.googleserviceaccount')),
                ('oauth_credential', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox', to='settings.oauthcredential')),
            ],
            options={
                'ordering': ['company__name', 'email_address'],
            },
        ),
    ]
