# Generated by Django 6.0.3 on 2026-03-11 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('last_history_id', models.CharField(blank=True, max_length=50)),
                ('watch_expiry', models.DateTimeField(blank=True, null=True)),
                ('watch_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('error', 'Error')], default='expired', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'mailboxes',
            },
        ),
    ]
